# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 262f7d1217d40ad54b5e94748ec74a97aecdc9dbbee98835f8ca84e568194148c00502e0800a83c78215e7a05b9adde4310d8201fdcf0088b12d775667acd287

test:
  secret_key_base: 5e3678d63617271f5f19dab6e276e9e310fc0f64e90d43c13a4d612d753b0c8b3bb64a0927bafb0e7b8b561e345350b4f6d809b6a07a038d4088fc35a902d695

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
